### ISSUE TITLE
11 Undeciphered Source Abbreviations

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#15]
https://github.com/sanskrit-lexicon/Cologne/issues/18#issuecomment-33067421 continued. Some <a href="https://docs.google.com/document/d/1we5kBbnznLn9eFe7ah-hpdClesBwLLITuwCLbJjbfrU/edit#heading=h.lvrw52f2why6">guesses</a>.

AdhyR. = आध्यात्म-रामायणम्
Du1ta7n3g. = दूताङ्गद
GrS3. = ? ग्रहणशान्ति, ग्रहशान्ति, ग्रहशान्तिपद्धति 
K. - ? Katyayana, Kielhorn
KaushBr. = कौशीतकी ब्राह्मणम्
Lokapr. = ? लोकप्रकाश, लोकप्रदोपान्वयचन्द्रिकानिदान
Ratnak.= ? रत्नाकर, रत्नाकरपद्धति, रत्नाकर ठक्कुर, रत्नाकर मिश्र
S3ambhMa1h. = शम्भुगिरिमाहात्म्य
S3rS. = श्रौतसूत्र 
S3r. = श्रौतसूत्र 
Sam2g. = ? संगीतकलिका

Until we find better solutions, I would propose to add it the "clean" file. 
Question marks mean - not sure. Otherwise - as sure as the rest of the "clean" list.

**Comment by gasyoun** [comment]
@zaaf2 and @drdhaval2785 - please help finalize MW abbreviations list. 11 missing still.

**Comment by gasyoun** [comment]
I thought the list is full, but today I stumpled upon `Caur.` Unknown literary source. How many `Unknown literary source` @funderburkjim are there such? So not only the initially listed 11? I proposed `Caur.` stands for `caurapañcāśikā` and as I've printed a Russian bilingua of it in 2020, I researched the file:

```
vidyā bandhujano videśagamane vidyā parā devatā
sujanabandhujaneṣvasahiṣṇutā
nāstyudyamasamo bandhuḥ kurvāṇo nāvasīdati || 2 ||
85 gajabhujaṃgavihaṃgamabandhanaṃ
samastabhāvaiḥ khalu bandhanaṃ striyaḥ || 2 ||
kandarpasyaikamitraṃ prakaṭitavividhaspaṣṭadoṣaprabandhaṃ
sneho na bandhuṣu na manmathajā vikārāḥ |
kṣīṇe bandhujane gate parijane naṣṭe śanairyauvane |
100 mātarmedini tāta māruta sakhe tejaḥ subandho jala
```

but all I found was in the `mahākaviśrībhartṛhariviracitaṃ` part. So I still believe in `caurapañcāśikā`, but a different edition of it.

![caur](https://user-images.githubusercontent.com/80761/103437389-366e2600-4c38-11eb-9dee-5b7ba72ff564.JPG)

**Comment by gasyoun** [comment]
http://ncc.sanskritdictionary.com/ contains 152526 entries.
https://youtu.be/yxxnqwdwKCU is not convenient to work for. It is https://www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2020/web/index.php AUFRECHT, T. (1891). Catalogus catalogorum - an update of it `42 volumes spanning November 1935 to October 2019`.

**Comment by Andhrabharati** [comment]
@funderburkjim / @gasyoun,

Is this issue closable now?

**Comment by funderburkjim** [comment]
The particular MW details of this issue are *probably* dated,
e.g. compare `Du1ta7n3g. = दूताङ्गद` above with line `Dūtāṅg.	Dūtāṅgada` in
[mwauth/tooltip.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/mw/pywork/mwauth/tooltip.txt#L123).

So this issue is closeable.

However, consider the question of consistency and completeness between:
* digitization markup of literary source abbreviations in csl-orig repository
* tooltips (expansions) of literary source abbreviations in csl-pywork repository

There are no general (applicable to all dictionaries) software tools for providing such consistency comparisons.  The [cologne repository](https://github.com/sanskrit-lexicon/COLOGNE/tree/master) might be a good home for such analytical tools. 

@drdhaval2785 Perhaps you would develop a python tool for analyzing ls-consistency?

As for this particular issue, I will close now.
