### ISSUE TITLE
Gram. 54 Link to Whitney Sanskrit Grammar

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#159]
@funderburkjim if there would be a one working sample, I could make a list of links to Whitney

![gram whitney](https://github.com/sanskrit-lexicon/MWS/assets/80761/8e74d339-16e6-402f-b339-14ae6a5f4597)

**Comment by Andhrabharati** [comment]
@gasyoun 
These Grammar citations are from MW's Grammar book, not Whitney's (unless [specifically mentioned thus](https://github.com/sanskrit-lexicon/MWS/issues/152#issuecomment-1423361028)), as I had pointed out recently at another issue (#44), reg. **Gr.**; the same applies to **Gram.** as well.

@funderburkjim 
I see that the tooltip is still showing Whitney at this 'ka' entry; I recall that you had changed the **Gr.** tooltip; the **Gram.** tooltip also needs a similar change.

[There are total 10 **Gram.** citations in MW.]

**Comment by Andhrabharati** [comment]
BTW, the 'a' after 836 is Roman letter, not Devanagari, here in mw.txt--
`<ls>Gram. 836</ls>. <s>a</s>`

![image](https://github.com/sanskrit-lexicon/MWS/assets/75209130/38c19055-d97b-47f6-b0f7-3e01792a5225)

**Comment by funderburkjim** [comment]
> the 'a' after 836 is Roman letter

Corrected.
<img width="115" alt="image" src="https://github.com/sanskrit-lexicon/MWS/assets/6393033/7534c7dc-8873-4a4f-bb0e-9de417039d93">

The 'a' appears as 'A' in display due to the charterindocapital font used for text within `<ls>Text</ls>`.

**Comment by funderburkjim** [comment]
'Gram.' ls tooltip abbreviation changed to `A Practical Grammar of the Sanskrit Language, Monier-Willilams`

**Comment by funderburkjim** [comment]
@gasyoun 

File [extract.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue159/extract.txt)  has all the (19) instances of `<ls>X</ls>` where X starts with "Gr." or "Gram.".

Apparently, there is some ambiguity as to whether a given instance of 'Gr.' actually refers to MW's grammar or Whitney's grammar,  and similarly for Gram.

You can examine these instances and appropriately replace the question mark with either 'mw' or 'whitney'.
For example, based on AB's investigation above under `; <L>41336.1<pc>240,3<k1>ka`
you would replace 
```
; <L>41336.1<pc>240,3<k1>ka
Gram. 836. a ::: ?
```
with
```
Gram. 836. a ::: mw
```
since Gram. here refers to Monier-Williams Grammar.

Then upload the revised extract.txt file.

You might also note the anomalies where 
* 'Gram.' is used but actually the reference is to Whitney grammar
* 'Gr.' is used, but actually the reference is to MW grammar.

@gasyoun Please confirm.

**Comment by Andhrabharati** [comment]
@gasyoun 

@funderburkjim's waiting time is nearing **6 months** shortly (in another week's time), for this simple task.

**Comment by funderburkjim** [comment]
I think the above commit finishes what remained to be done.
