### ISSUE TITLE
homophone corrections in MW

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#22]
Material for current work on homophone corrections in MW has been uploaded to the
[homophone](https://github.com/sanskrit-lexicon/MWS/tree/master/homophone) directory.
There is a readme.txt file in that directory.  As mentioned there, this work is based on work by Pawan and
Peter from 2013.  The correction work is probably close to completion (but not quite completed). There are
still some 'TODO' cases, which others may want to examine.

**Comment by gasyoun** [comment]
By `'referential' homonym` you mean some numbers introduced in the digital copy (like `0` for the first word) that are logical, but unprinted in the book, right? I hope you understand that you can not be sure at this level of analysis if we have homophone or homograph. Otherwise perfect as always. Collecting all the documentation would make a book as big as Bible.

**Comment by funderburkjim** [comment]
`referential homonym` is a term I made up to refer to a certain kind of situation, exemplified by the first
record (L=4387) for aDyuzita, whose content is
```
» s.v.    [in display]
<see/> s.v.   [approximate underlying xml]
```
So all this record does is *point to* some other record;  hence it is referential,  and since the thing it refers
to is another entry with the same spelling,  it can be called a 'referential homonym'.

In the work that Pawan and Peter did,  such records as L=4387 were identified as components of a 
homonym set, and since this record was not already assigned a homonym number by MW, Pawan assigned it a provisional homonym number of 0.   It is possible that some records were assigned homonym numbers of 0 for some other reason,  so we don't know a priori that an assignment by Pawan's programs of a homonym number of 0 for some record necessarily entails that the record is a referential homonym.  

One other small point in the markup.  The actual markup of the 4387 content is currently:
```
<see type="nonhier"/> <ab>s.v.</ab>
```
That type="nonhier" attribute assignment for the 'see' tag was something I introduced at some time, when
I was thinking about how the list display might be improved.  With it, one can readily identify a record as
being totally referential.  The value term 'nonhier'  is an abbreviation for 'non-hierarchical';  my thinking can be
exemplified by aDyuzita.  Think of looking up aDyuzita in the list display, and ask yourself the question: 'Which of the L-numbers (4387, 4692, 4693) should serve as the center of the left pane context list?`

My answer to this question was 4692; since 4387 is totally referential, it is not a 'real' homonym but a print dictionary dinosaur.  In order to know to skip 4692, I introduced the type='nonhier'  attribute of 'see' tag which was easy to search for during the construction of the list display list.  This is the way the current list display functions. 

However, suppose one DID want to see the contextual list at 4387 ? Currently, the display does not support switching the context list to another homonym.  Pawan developed a version of list display which, among a
few other things, does support this switching.  That seems like a good idea, and I'll probably implement it at some point in the Cologne display.

**Comment by gasyoun** [comment]
@funderburkjim can you please compile a list of "totally referential" entries or add a tag to the lex gramm MW? Or just regexing for `nonhier` should help me?
As per the general idea of 'referential homonym' http://en.wiktionary.org/wiki/varia_lectio might be the scientific name, I guess.

**Comment by funderburkjim** [comment]
@gasyoun  The regex used in the list display is
```
<see type="nonhier"/>
```
So that is what I would use to select all the MW records marked as 'totally referential'.  Using grep in gitbash shell for Windows:
```
grep '<see type="nonhier"/>' monier.xml > nonhier.txt
wc -l nonhier.txt
 4469 nonhier.txt   [number of records in the file]
```

I don't think 'varia lectio' is the same notion.  MW also uses the 'v.l' abbreviation. 
```
grep 'v[.]l[.]' monier.xml > vlfilter.txt
Then
wc -l vlfilter.txt
 3537 vlfilter.txt   
```
First example in vlfilter.txt is headword `agnizwut`, where we see
`v.l. -ṣṭubh`, which indicates that an alternate reading of agnizwut is agnizwuB,  so we're not talking homonyms here.

**Comment by funderburkjim** [comment]
re homonym v. homophone v. homograph.

I used the term 'homophone' in the description of Pawan/Peter work since that is the term they used.
I prefer the term homonym.   Some online references state that 'homonym' refers to the spelling, and 
'homophone' refers to the sound.   So using English language examples, 'go' (the verb) and 'go' (the board game) would be homonyms;  'bear' (the animal) and 'bare' (without covering) would be homophones.

For Sanskrit,  which bills itself as spelling words phonetically, the two notions (homonym and homophone) seem interchangeable to me.    
However,  there may be distinctions regarding nasals  (homorganic or anusvara) even in Sanskrit - so aNka and aMka may be considered homophones but not homonyms in Sanskrit -  I'm not sure.   

Your usage of 'homograph' was new to me, and I'm not sure whether it fits into the discussion for Sanskrit.
The Google search definition shows
```
each of two or more words spelled the same but not necessarily pronounced the same and having different meanings and origins (e.g., bow1 and bow2).
```
Applied to Sanskrit, this case would never occur, since two identically spelled Sanskrit words would definitely be pronounced the same.

**Comment by gasyoun** [comment]
Interchangeable - agree. As regarding the panchavargama cases - as an output of simplification it could lead us in trouble indeed.
Homographs are words which are spelled the same, but with more than one meaning. Homographs may be pronounced the same (homophones), or they may be pronounced differently (heteronyms, also known as heterophones).
I'm sorry to add, that `Applied to Sanskrit, this case would never occur, since two identically spelled Sanskrit words would definitely be pronounced the same.` is not true. In natural language conditions it indeed could hardly occur, but in dictionaries - time to time. If we make abstractions such as verb roots we create an abstraction that can be shared for several different words and is only because of the written form. It this case spelling is secondary. Or there might be a frozen verb form that matches some already existing word. I'm sorry not to provide examples and lete homonym be the term, but strictly scientifically speaking if I'll examine all the pretendants I'll point out those that are not `pure`.

**Comment by funderburkjim** [comment]
Artificial homophones have been assigned to 10,913 records of MW.  A discussion is 
[here](https://github.com/sanskrit-lexicon/MWS/blob/master/homophone/readme.txt).

**Comment by gasyoun** [comment]
Now I'm aware of `unique (numeric) homophone code`, interesting meta data. I hope Dhaval undestands why this or that is needed, after reading there is mess in my head, maybe because I had a two week trip and still do not remember how to switch on my PC. Are the `10,913 records` to-be manually examined now?
