### ISSUE TITLE
bug: prAYc

### ISSUE THREAD

**Issue by mbykov** [sanskrit-lexicon/MWS#29]
"key1: <key1>prAYc</key1>" - "key2: <key2>prAk</key2>"
should be prAYc

**Comment by funderburkjim** [comment]
This is L=139203.

Agree that key1 and key2 should be consistent; so there is an error here.

 But, I think the error is in key1, which should be 'prAk'

**Comment by funderburkjim** [comment]
@mbykov   Hello!   This comment is a suggestion about when to 'Close' an issue.

The usual practice is to leave an issue 'open' until it has been resolved.   In an issue like this one, where you have pointed out an error that needs to be corrected,  you would leave it open.

Then, since it is up to me to act on the correction (i.e., to install the correction at Cologne),
 I would normally be the one to close the issue when I've done my part.

So, I'm now going to reopen the issue.  

And, when I've installed the correction, I'll come back and close it.

Of course, if you disagree with the way I've made the correction, you could reopen it once again for further discussion.

I'll deal with #30, #31, etc. similarly.

**Comment by funderburkjim** [comment]
@mbykov Another small suggestion regarding correction submission.   

It is helpful to me for you to include mention of the 'L-number' of the MW record under discussion.
Especially in a case such as this, where there are many headwords in MW with key1=prAYc,  this L number helps to narrow down my search for exactly which record needs to be corrected.

**Comment by funderburkjim** [comment]
Corrections installed.
