### ISSUE TITLE
&c -> &c.

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#47]
(H1) sthal [p= 1261] : (connected with √1. sthā) cl.1 P. sthalati, to stand firm, be firmDhātup.  xx, 6. [cf. Gk. στέλλω, στόλος ; Germ. stellen, still &c ; Eng. still.] [L=255204]

&c can never occur without a dot. Should not we mark it as an abbreviation?

**Comment by funderburkjim** [comment]
Agree, there should be a period.

In mw,  the ampersand is actually coded as a tag  (either `<etc/>` or `<etc1>`.)  This is because of the
arcane aspect of xml that the ampersand character can't appear on its own.  One solution is to
replace it by the xml-entity `&amp;`.   So `<text> this &amp; that</text>`.

Instead of that solution, in mw.xml I chose to represent it via empty tags, as above.  

disp.php governs how these empty tags are displayed.  Formerly, as you noticed,  the representation
was `&amp;c`  (no period).

I've now changed this to `&amp;c.`  (with a period).

![image](https://user-images.githubusercontent.com/6393033/32303632-17b85664-bf40-11e7-8515-668ebe046298.png)

**Comment by gasyoun** [comment]
> One solution is to replace it by the xml-entity &amp;

Does not sound bad at all.

> I've now changed this to &amp;c. (with a period).

In just this case or all around?

**Comment by funderburkjim** [comment]
> In just this case or all around?

Since the change was to the display program (disp.php) for MW,  the change applies to displays of all MW headwords.

**Comment by gasyoun** [comment]
> change applies to displays of all MW headwords.

(H1) kīra [p= 285] : m. a parrot Vet.  &c [L=50759]

![kira](https://user-images.githubusercontent.com/80761/32352143-030de1b0-c031-11e7-930f-88fdefc28e47.PNG)

Does not seem so, Jim

**Comment by funderburkjim** [comment]
As far as I can tell, the issue with the period here after '&c' is fully solved.  If more remains to be done,
please mention.

**Comment by gasyoun** [comment]
> As far as I can tell, the issue with the period here after '&c' is fully solved.

Indeed, everywhere outside http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html it's fixed. Let me see further if any cases occur.

**Comment by funderburkjim** [comment]
The recent changes to abbreviations and tooltips should now appear in list-0.2s and related displays.

I am aware of two kinds of issues:
1) L = and p=  tooltips do not appear in the list-0.2 displays.  I will address this problem soon.
2) Although I've added `<ab>` tag in mw.xml to thousands of previously unmarked abbreviations, there
    are still some instances which have eluded the markup.  Let me know when you discover these, and I'll  add the markup.

**Comment by gasyoun** [comment]
> Let me know when you discover these, and I'll add the markup.

Sure.

> list-0.2s

Well done. What about providing a link to it from homepage?

**Comment by funderburkjim** [comment]
Got tooltips for L= and p= implemented for list-0.2s. Easier than expected.

> Add list-0.2s to home page.

OK.
a) What design do you want for link.
b) Maybe a help link on list-0.2s page is needed ?
    Would you write?

**Comment by gasyoun** [comment]
> a) What design do you want for link.

New Display (Dec 2016)  -> New Simple Display (Dec 2017)

> b) Maybe a help link on list-0.2s page is needed ?

Sure.

> Would you write?

Yes, and make a video, but first launch it. I'll follow up.
