### ISSUE TITLE
AS in sources still alive? DivyA7v. 

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#50]
Was not AS in abbreviations killed by now in MW?

> (H1C) sarvam : ind. (with sarveṇa) completely DivyA7v.  [L=238110]

**Comment by funderburkjim** [comment]
There are two details here:
1) The upper case A in A7 is a typo; should be a7.
![image](https://user-images.githubusercontent.com/6393033/32575352-c30a25ea-c4a1-11e7-943e-b11d6bf2a60b.png)

2) how to transcode the a7 to IAST.   I've made the choice to transcode it to macron  (consistent with mwauthorities), rather than circumflex (consistent with printed text).

(H1C) sarvam [p= 1184,3] [L=238110]	ind. (with sarveṇa) completely Divyāv. 

Recall that in the MW print, the circumflex indicates a long vowel resulting from vowel sandhi,
e.g. divya + avadAna -> divy**A**vadAna.

**Comment by gasyoun** [comment]
>  transcode it to macron (consistent with mwauthorities), rather than circumflex (consistent with printed text).

That's something to think about.

> Recall that in the MW print, the circumflex indicates a long vowel resulting from vowel sandhi

Maybe get macron's back and add a tooltip for each case that it's a sandhi, @SergeA ?

**Comment by gasyoun** [comment]
> [p= 1323] : ( VS.  ; also) N. of Gan2es3a's wife, RTL.  215 [L=38940.1]

Gan2es3a's - I was thinking we are done with AS in MW.

**Comment by funderburkjim** [comment]
The reason this shows up as it does is that it is missing the `<aso>, <as1>` coding normally used for
such situations.  I will enter a correction to bring this into line with this system.

See #55 for documentation of current system.

**Comment by gasyoun** [comment]
@funderburkjim time to close?

**Comment by funderburkjim** [comment]
Agree with close.   AFAIK,  the AS coding is absent in current digitizations of all dictionaries.
