### ISSUE TITLE
ifc. f (ā) .

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/MWS#57]
>  (ifc. f (ā) . MBh.  xiii, 3700 ) [L=59661]

`f` not marked as such, because dot only after (ā) .

> mf (ā) n. endowed with auspicious signs or marks, lucky, fortunate L.  [L=180475]

`mf (ā) n.` same unmarkedness.

> (H3) nāga-bala [p= 533] : m. "having the strength of an elephant", N. of bhīma L.  [L=105059]

`N.` unmarked.

**Comment by funderburkjim** [comment]
Changing the xml to html is tricky in this circumstance.  
The xml looks like `<lex type="hwifc">f (<s>A</s>) .</lex>`.
In the current system, a tooltip is added at display time, and we must recognize that there needs to be
one for the 'f'.   This is tricky, because of the other stuff in the lex tag:  ` (<s>A</s>) .`
Anyway, I modified disp.php (which generates the html from xml) to handle this.  It is currently
implemented in the basic and other displays.  Will migrate to list-0.2s display in due course of events.

The gender examples you gave are for headwords kzIra, lakzmaRa,
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/indexcaller.php?key=kzIra&input=slp1&output=deva


The  last example  (nAgabala)  is different in solution.  Here there is missing 'ab' tag markup;
i.e., `N.` -> `<ab>N.</ab>` is the solution.

Also, I checked for similar `N.` missing the abbreviation tag and found 6000+ (when requiring 
a space be on either side of `N.`.).

Will apply changes to these 6000+ cases so they have `<ab>N.</ab>` markup.

**Comment by drdhaval2785** [comment]
@gasyoun and @funderburkjim any update ? These 6000 items corrected?

**Comment by funderburkjim** [comment]
I think these 6000 items likely corrected, as 'N.' shows as abbreviation in nAga-bala:

![image](https://user-images.githubusercontent.com/6393033/102023646-07f8db80-3d5b-11eb-9ca5-85575547a6f8.png)

Also, the two other problems noted (for MW headwords kzIra, lakzmaRa) are resolve.

Can close.
