### ISSUE TITLE
IdfSa mw.txt issue

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/MWS#92]
I think there is some information loss in this case.
mw.txt has the following item.

The data before `endowed` seems to be lost.

```
<L>29743<pc>170,2<k1>IdfSa<k2>Idf/Sa<e>2
<s>Idf/Sa</s> ¦ <lex>mf(<s>I</s>)n.</lex>  endowed with such qualities, such, <ls>ŚBr.</ls>; <ls>ChUp.</ls>; <ls>Mn.</ls>; <ls>R.</ls>; <ls>Bhag.</ls> : <ls>Śak. &c.</ls><info or="29743,IdfSa;29745,IdfSaka"/><info lex="m:f#I:n"/>
<LEND>
<L>29744<pc>170,2<k1>IdfSa<k2>IdfSa<e>2E
<s>IdfSa</s> ¦ [with the final syllables <s>dfS</s> and <s>dfSa</s> of these words <ab>cf.</ab> the <ab>Gk.</ab> <lang n="greek">λικ</lang> in <lang n="greek">ὑμῆλιξ</lang>, <lang n="greek">λικο</lang> in <lang n="greek">τηλίκο-ς</lang> &c.; <ab>Goth.</ab> <etym>leika</etym> in <etym>hvêleiks</etym>, ‘which one’, <etym>svaleik-s</etym>, ‘such’; <ab>Mod.</ab> <ab>Germ.</ab> <etym>welcher</etym>, <etym>solcher</etym>; <ab>Slav.</ab> <etym>liko</etym> <ab>nom.</ab> <etym>lik</etym> <ab>e.g.</ab> <etym>tolik</etym>, ‘such’; <ab>Lat.</ab> <etym>li</etym> in <etym>tâlis</etym>, <etym>quâlis</etym>.]
<LEND>
```

**Comment by drdhaval2785** [comment]
![capture](https://user-images.githubusercontent.com/5755132/103474638-df995580-4dcb-11eb-859d-ddde2ce7e699.PNG)

**Comment by drdhaval2785** [comment]
```
<L>29745<pc>170,2<k1>IdfSaka<k2>IdfSaka<e>2
<s>IdfSaka</s> ¦  <lex>mf(<s>ikA</s>)n.</lex> endowed with such qualities, such, <ls>ŚBr.</ls>; <ls>ChUp.</ls>; <ls>Mn.</ls>; <ls>R.</ls>; <ls>Bhag.</ls> : <ls>Śak. &c.</ls><info or="29743,IdfSa;29745,IdfSaka"/><info lex="m:f#ikA:n"/>
<LEND>
```

**Comment by Andhrabharati** [comment]
> 
> 
> I think there is some information loss in this case.
> mw.txt has the following item.
> 
> The data before `endowed` seems to be lost.
> 
> ```
> <L>29743<pc>170,2<k1>IdfSa<k2>Idf/Sa<e>2
> <s>Idf/Sa</s> ¦ <lex>mf(<s>I</s>)n.</lex>  endowed with such qualities, such, <ls>ŚBr.</ls>; <ls>ChUp.</ls>; <ls>Mn.</ls>; <ls>R.</ls>; <ls>Bhag.</ls> : <ls>Śak. &c.</ls><info or="29743,IdfSa;29745,IdfSaka"/><info lex="m:f#I:n"/>
> <LEND>
> <L>29744<pc>170,2<k1>IdfSa<k2>IdfSa<e>2E
> <s>IdfSa</s> ¦ [with the final syllables <s>dfS</s> and <s>dfSa</s> of these words <ab>cf.</ab> the <ab>Gk.</ab> <lang n="greek">λικ</lang> in <lang n="greek">ὑμῆλιξ</lang>, <lang n="greek">λικο</lang> in <lang n="greek">τηλίκο-ς</lang> &c.; <ab>Goth.</ab> <etym>leika</etym> in <etym>hvêleiks</etym>, ‘which one’, <etym>svaleik-s</etym>, ‘such’; <ab>Mod.</ab> <ab>Germ.</ab> <etym>welcher</etym>, <etym>solcher</etym>; <ab>Slav.</ab> <etym>liko</etym> <ab>nom.</ab> <etym>lik</etym> <ab>e.g.</ab> <etym>tolik</etym>, ‘such’; <ab>Lat.</ab> <etym>li</etym> in <etym>tâlis</etym>, <etym>quâlis</etym>.]
> <LEND>
> ```

There are 4 or 5 such cases in the whole data, noticed at my very initial look at xml data!!

> 
> 
> ![capture](https://user-images.githubusercontent.com/5755132/103474638-df995580-4dcb-11eb-859d-ddde2ce7e699.PNG)

I see plenty of such ones in the data.

Guess they are all crept in when the "grouped" entries (as were earlier) are split as separate entries (as at present).

**Comment by Andhrabharati** [comment]
I've so many issues like these identified; but you guys are no way near handling (attending to) them "all at once".

So one has to tell only one issue at a time, to suit your way of working.

[I see that Jim wants to closely (rather too close at microscopic level!) look at each issue, and spend more time in documenting it to that extent, which I think, is taking more time which could've been otherwise effectively used for other tasks, by looking into the issues at just macroscopic level. **Sorry if if I had hurt anyone with such comments, but that's what I feel from the bottom of my heart.**]

**Comment by drdhaval2785** [comment]
> I've so many issues like these identified

 It would be nice if you can note them somewhere in github issue. It would be workable.

> Jim wants to closely (rather too close at microscopic level!) look at each issue

Yes. And there is no harm in being conservative.

> looking into the issues at just macroscopic level. 

I have seen Jim working for close to six years now. I am yet to see a time when he does not make a generic change when he spots one. Whenever there is something which is generic in nature, he addersses it generically. 

By doing 'all at once', if you intend to say that one is going to read each page of dictionary and make necessary corrections, it is fine. But I am yet to see any such volunteer for any dictionary. 
If anyone so volunteers, it would be a pleasure.

But as the generation of xml, html, sqlite etc are based on me.txt file, its structure should and can not be changed without corresponding changes in the code.

**Comment by drdhaval2785** [comment]
And despite difference of opinion about ways of working, our end goal seems the same. It is nice to see that you are dedicating your time to this cause. We do not get volunteers very easily. 2020 seemed to be a different year. Anna and you are great addition @Andhrabharati .

**Comment by gasyoun** [comment]
> I have seen Jim working for close to six years now. I am yet to see a time when he does not make a generic change when he spots one. Whenever there is something which is generic in nature, he addersses it generically.

Exactly.

> By doing 'all at once', if you intend to say that one is going to read each page of dictionary and make necessary corrections, it is fine. But I am yet to see any such volunteer for any dictionary.
If anyone so volunteers, it would be a pleasure.

Indeed.

> Anna and you are great addition @Andhrabharati .

Yes, I would say the greatest addition we had in a while and one yet to show it's strength.

**Comment by funderburkjim** [comment]
First, note that there is some 'meta' information in mw.txt for both  IdfSa and IdfSaka that  indicates these were linked in the print:  `<info or="29743,IdfSa;29745,IdfSaka"/>`   There are about 6000 `<info or`
instances indicating roughly 3000 printed `or` entries.

Incidentally, there is also similar markup with 'and', such as `<info and="535,akza;536,akzacaraRa"/>`.
There are about 1500 `and` records, indicating about 750 printed `and` entries.

These are inherently difficult to fit into the scheme of *records with headwords* that we adopted early
on as a way to usefully 'digitize' Monier-Williams 1899; and that I then adopted as a way to
similarly organize Thomas Malten's digitization of other dictionaries.

We might abstract this  kind of MW print as `A x OR B y`, where A and B are the headwords.  In order to fit this into the headword-entry model of the digitization, we  must construct `A z` and `B w`, where z and
w are somehow constructed out of x and y.

In our case of IdfSa and IdfSaka,  x is just `<lex>mf(<s>I</s>)n.</lex>` and y is 
`<lex>mf(<s>ikA</s>)n.</lex> endowed with ...<ls>Śak. &c.</ls>
 [with the final syllables ... <etym>quâlis</etym>.]`

In coming up with the 'z' and 'w',  I thought of y as `y1 y2 y3`, where
* y1 = `<lex>mf(<s>ikA</s>)n.</lex>` , 
* y2 = `endowed with ...<ls>Śak. &c.</ls>`
* y3 = `[with the final syllables <s>dfS</s> and <s>dfSa</s> ... <etym>quâlis</etym>.]`

And then decided that  
* z = `x y2 y3`   the part that pertains to A = IdfSa
* w = `y1 y2`     the part that pertains tp B = IdfSaka.  Note that 'y3' does not appear in IdfSaka,
   which seems semantically defensible, but probably debatable.

That is the kind of rationale that led to the current markup.

To me, it still seems reasonable.

With the possible exception that there is currently nothing that appears in the display indicating the
original print linkage, since the '<info or=`  code currently plays no role in the displays.

That's enough background for this particular comment.

Let me ask @drdhaval2785, whose original question mentioned 'information loss'.

How would you propose to change the coding to restore the lost information?

**Comment by drdhaval2785** [comment]
> Let me ask @drdhaval2785, whose original question mentioned 'information loss'.

I posted the question first and then saw the entry 
```
<L>29745<pc>170,2<k1>IdfSaka<k2>IdfSaka<e>2
<s>IdfSaka</s> ¦  <lex>mf(<s>ikA</s>)n.</lex> endowed with such qualities, such, <ls>ŚBr.</ls>; <ls>ChUp.</ls>; <ls>Mn.</ls>; <ls>R.</ls>; <ls>Bhag.</ls> : <ls>Śak. &c.</ls><info or="29743,IdfSa;29745,IdfSaka"/><info lex="m:f#ikA:n"/>
<LEND>
```

After taking into account your explanation and this entry, I do not see any information loss now. 
Thanks for the explanation.

**Comment by Andhrabharati** [comment]
> 
> We might abstract this kind of MW print as `A x OR B y`, where A and B are the headwords. In order to fit this into the headword-entry model of the digitization, we must construct `A z` and `B w`, where z and
> w are somehow constructed out of x and y.
> 

Glad to see this point coming up here.

From the very beginning of our Dictionary work, we have this treated quite appropriately.
Pl. have a look at the screenshot for the result.

**You don't need to understand the words there, it is all in Telugu.**
Just look at the search word in Bold at the top, and the entry word(s) in each dictionary where it is found, either individually or in a group.

For the grouped items, the search of any of the individual member give the group list. We just had the HW (standalone or separated from a group) in one field, and the dictionary entry as is (standalone or group) in another. [Quite simple logic.]

![image](https://user-images.githubusercontent.com/75209130/103505916-7aa03700-4e81-11eb-9a2c-3f52b96c0395.png)

Each dictionary content is given one below the other, in the result screen, picked up from all the currently available (digitized) ones in the database.

**Comment by gasyoun** [comment]
> We might abstract this kind of MW print as A x OR B y, where A and B are the headwords. In order to fit this into the headword-entry model of the digitization, we must construct A z and B w, where z and
w are somehow constructed out of x and y.

Now I start to understand.

> Each dictionary content is given one below the other, in the result screen, picked up from all the currently available (digitized) ones in the database.

Yes, hope we get here as well, if Jim likes the `Global` idea.

**Comment by Andhrabharati** [comment]
Hope so!, and there is a Dictionary selection option provided at the top right-side group, which allows the user to particularly search only within the work(s) he is interested in.

BTW, there are ~50 works already online here and about 10-12 soon to be there. All data is ready, just waiting to get them ported into the DB.
